#!/bin/bash

# this lists VBox VMs, wakes one you choose as headless and connects to it via ssh

VMsList=(` VBoxManage list vms | grep -o '".*"'  | tr -d '"' `) # lists all VMs registered to VBox Manager
ipRegExp=([0-9]{1,3}[\.]){3}[0-9]{1,3};

for ((i=0; i<=(${#VMsList[@]} -1); i++))
do
   echo "$[i+1]: ${VMsList[$i]}"
done
echo "choose VM by number"
read VMnumber;							# reads your choice
VMname=`echo "${VMsList[$[VMnumber-1]]}"`			# gets name of the VM, then its ip
VMip=`VBoxManage guestproperty enumerate $VMname | grep -E -o "/GuestInfo/Net/0/V4/IP, value: $ipRegExp" | grep -E -o $ipRegExp`;
VMuser="vuser"							# in my case. you may want to 'read' it
gnome-terminal -x sh -c "VBoxManage startvm $VMname --type headless; 
ssh $VMuser@$VMip;
VBoxManage controlvm educ-lin savestate;"			# stops the VM after ssh logout. you may want to comment this
